name: Publish

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'The semantic version segment to increment'
        required: true
        default: feature
        type: choice
        options:
          - major
          - feature
          - bug

jobs:
  publish-package:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish to Sonatype
        id: publish-to-sonatype
        env:
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          ORG_GRADLE_PROJECT_signingKey=$(echo -e "$ORG_GRADLE_PROJECT_signingKey")
          ./gradlew -Dorg.gradle.project.version=3.2.3 publishToSonatype closeAndReleaseSonatypeStagingRepository
